include:
#- ./../../configs/hw/boards/pic32mz_memory.yml
- ./syms.yml

memory_map:
  sram:
    base_addr: 0x80000000
    file: ./blinky.X.production.elf
    permissions: rw-
    size: 0x80000
    file_offset: 0x010000
  text:
    base_addr: 0x9d000000
    file: ./blinky.X.production.elf
    permissions: r-x
    size: 0x5000
    file_offset: 0x020000
  boot:
    base_addr: 0xbfc00000
    file: ./blinky.X.production.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x040000
    is_entry: True
  mmio: 
    base_addr:  0xbf800000
    size: 0x100000
    permissions: rw-
# handlers:
#  SYS_Initialize: null
 
arch: MIPS32
endianness: LE
initial_sp: 0x8007fff8
entry_point: 0xbfc00000

use_timers: false
use_nvic: false
use_systick: false
