include:
#- ./../../configs/hw/boards/pic32mz_memory.yml
- ./syms.yml

memory_map:
  sram:
    base_addr: 0xa0000000
    permissions: rw-
    size: 0x20000
  text:
    base_addr: 0x9d000000
    file: ./basic_exercises.elf
    permissions: r-x
    size: 0x5000
    file_offset: 0x10000
  isr:
    base_addr: 9fc01000
    file: ./basic_exercises.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x021000
  boot:
    base_addr: 0xbfc00000
    file: ./basic_exercises.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x040000
    is_entry: True
  mmio_1:
    base_addr: 0xbf800000
    size: 0x10000
    permissions: rw-
  mmio_2:
    base_addr: 0xbf882000
    size: 0x5000
    permissions: rw-
  interrupt_control_registers:
    base_addr: 0xbf881000
    size: 0x1000
    permissions: rw-

interrupt_triggers:
  idle_irq:
    every_nth_tick: 200
    fuzz_mode: round_robin
  #random_irq:
  #  addr: xTaskGetTickCount
  #  fuzz_mode: round_robin
   
  #RTOS_timer:
    # time-based
  #  addr: xTaskGetTickCount
    # fixed irq number
  #  irq: 4
  #RTOS_timer2:
  #  addr: xTaskResumeAll
  #  irq: 4

handlers:
  #UART1_Read:
  #  handler: fuzzware_harness.user_hooks.fuzz.return_fuzz_byte
  #  do_return: True
  UART1_Write: null

use_nvic: true  
nvic:
  # interrupt vector base address (alternative name: 'addr')
  vtor: 0
  # configure the maximum number of vectors in the nvic, defaults to 256
  num_vecs: 256
  processor: pic32mx4XX
  disabled_irqs: [38]


arch: MIPS32
endianness: LE
initial_sp: 0xa001fff8
entry_point: 0xbfc00000

use_systick: false
