include:
- ./../../configs/hw/cortexm_memory.yml
- ./syms.yml

memory_map:
  text:
    base_addr: 0x8000000
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
    is_entry: True

use_timers: false
use_nvic: false
use_systick: false
