include:
#- ./../../configs/hw/boards/pic32mz_memory.yml
- ./syms.yml

memory_map:
  sram:
    base_addr: 0x80000000
    permissions: rw-
    size: 0x20000
  text:
    base_addr: 0x9d000000
    file: ./basic_exercises.elf
    permissions: r-x
    size: 0x7500
    file_offset: 0x020000
  boot:
    base_addr: 0xbfc00000
    file: ./basic_exercises.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x040000
    is_entry: True
  mmio_1:
    base_addr: 0xbf800000
    size: 0x10000
    permissions: rw-
  mmio_2:
    base_addr: 0xbf811000
    size: 0xe9000
    permissions: rw-
  interrupt_control_registers:
    base_addr: 0xbf810000
    size: 0x1000
    permissions: rw-

handlers:
  CORETIMER_DelayMs: null
  __wrap_sprintf: null
  #UART2_ReadIsBusy: null
  #UART2_Read:
  #  handler: fuzzware_harness.user_hooks.fuzz.return_fuzz_byte
  #  do_return: True
 
interrupt_triggers:
  idle_irq:
    every_nth_tick: 200
    fuzz_mode: round_robin 


use_nvic: true 
use_timer: true
nvic:
  # interrupt vector base address (alternative name: 'addr')
  vtor: 0
  # configure the maximum number of vectors in the nvic, defaults to 256
  num_vecs: 256
  processor: pic32mz

 
arch: MIPS32
endianness: LE
initial_sp: 0x8001FFF8
entry_point: 0xbfc00000

use_systick: false
