include:
  - ./../cortexm_memory.yml

memory_map:
  ivt: {base_addr: 0x0, file: '*.bin',
    permissions: r-x, size: 0x80000}
  rom: {base_addr: 0x80000, file: '*.bin',
    permissions: r-x, size: 0x800000, is_entry: True}
