include:
  - ./../cortexm_memory.yml

memory_map:
  #ivt: {base_addr: 0x0, file: '*.bin',
  #  permissions: r-x, size: 0x800000}
  text: {base_addr: 0x08000000, file: '*.bin',
    permissions: r-x, size: 0x800000, is_entry: True}